def BaseHTTPRequestHandler(*args, **kwargs): pass
def Camera(*args, **kwargs): pass
def GSprint(*args, **kwargs): pass
def GSversion(*args, **kwargs): pass
def GW(*args, **kwargs): pass
def GlowWidget(*args, **kwargs): pass
def HTTPServer(*args, **kwargs): pass
def INTERACT_PERIOD(*args, **kwargs): pass
def MAX_RENDERS(*args, **kwargs): pass
def MIN_RENDERS(*args, **kwargs): pass
def MISC(*args, **kwargs): pass
def Mouse(*args, **kwargs): pass
def RackOutline(*args, **kwargs): pass
def RateKeeper(*args, **kwargs): pass
def ToothOutline(*args, **kwargs): pass
def USER_FRACTION(*args, **kwargs): pass
def WSserver(*args, **kwargs): pass
def WebSocketServerFactory(*args, **kwargs): pass
def WebSocketServerProtocol(*args, **kwargs): pass
def absolute_import(*args, **kwargs): pass
def acos(*args, **kwargs): pass
def acosh(*args, **kwargs): pass
def addpos(*args, **kwargs): pass
def adjust_axis(*args, **kwargs): pass
def adjust_up(*args, **kwargs): pass
def arange(*args, **kwargs): pass
def arrow(*args, **kwargs): pass
def asin(*args, **kwargs): pass
def asinh(*args, **kwargs): pass
def asyncio(*args, **kwargs): pass
def atan(*args, **kwargs): pass
def atan2(*args, **kwargs): pass
def atanh(*args, **kwargs): pass
def attach_arrow(*args, **kwargs): pass
def attach_trail(*args, **kwargs): pass
def baseObj(*args, **kwargs): pass
def box(*args, **kwargs): pass
def bumpmaps(*args, **kwargs): pass
def button(*args, **kwargs): pass
def canvas(*args, **kwargs): pass
def ceil(*args, **kwargs): pass
def checkbox(*args, **kwargs): pass
def clock(*args, **kwargs): pass
def color(*args, **kwargs): pass
def colorsys(*args, **kwargs): pass
def combin(*args, **kwargs): pass
def comp(*args, **kwargs): pass
def compound(*args, **kwargs): pass
def cone(*args, **kwargs): pass
def controls(*args, **kwargs): pass
def convert(*args, **kwargs): pass
def copy(*args, **kwargs): pass
def copysign(*args, **kwargs): pass
def cos(*args, **kwargs): pass
def cosh(*args, **kwargs): pass
def cross(*args, **kwargs): pass
def curve(*args, **kwargs): pass
def curveMethods(*args, **kwargs): pass
def cylinder(*args, **kwargs): pass
def cyvector(*args, **kwargs): pass
def degrees(*args, **kwargs): pass
def diff_angle(*args, **kwargs): pass
def distant_light(*args, **kwargs): pass
def division(*args, **kwargs): pass
def dot(*args, **kwargs): pass
def e(*args, **kwargs): pass
def ellipsoid(*args, **kwargs): pass
def erf(*args, **kwargs): pass
def erfc(*args, **kwargs): pass
def event_return(*args, **kwargs): pass
def exp(*args, **kwargs): pass
def expm1(*args, **kwargs): pass
def extrusion(*args, **kwargs): pass
def fabs(*args, **kwargs): pass
def faces(*args, **kwargs): pass
def factorial(*args, **kwargs): pass
def fd(*args, **kwargs): pass
def find_free_port(*args, **kwargs): pass
def floor(*args, **kwargs): pass
def fmod(*args, **kwargs): pass
def frame(*args, **kwargs): pass
def frexp(*args, **kwargs): pass
def fsum(*args, **kwargs): pass
def gamma(*args, **kwargs): pass
def gcd(*args, **kwargs): pass
def gcurve(*args, **kwargs): pass
def gdots(*args, **kwargs): pass
def ghbars(*args, **kwargs): pass
def glowcomm(*args, **kwargs): pass
def gobj(*args, **kwargs): pass
def graph(*args, **kwargs): pass
def gs_version(*args, **kwargs): pass
def gvbars(*args, **kwargs): pass
def hat(*args, **kwargs): pass
def helix(*args, **kwargs): pass
def httpserving(*args, **kwargs): pass
def hypot(*args, **kwargs): pass
def inf(*args, **kwargs): pass
def inspect(*args, **kwargs): pass
def isclose(*args, **kwargs): pass
def isfinite(*args, **kwargs): pass
def isinf(*args, **kwargs): pass
def isnan(*args, **kwargs): pass
def js(*args, **kwargs): pass
def json(*args, **kwargs): pass
def label(*args, **kwargs): pass
def ldexp(*args, **kwargs): pass
def lgamma(*args, **kwargs): pass
def list_to_vec(*args, **kwargs): pass
def local_light(*args, **kwargs): pass
def log(*args, **kwargs): pass
def log10(*args, **kwargs): pass
def log1p(*args, **kwargs): pass
def log2(*args, **kwargs): pass
def long(*args, **kwargs): pass
def mag(*args, **kwargs): pass
def mag2(*args, **kwargs): pass
def menu(*args, **kwargs): pass
def meta_canvas(*args, **kwargs): pass
def modf(*args, **kwargs): pass
def nan(*args, **kwargs): pass
def no_notebook(*args, **kwargs): pass
def norm(*args, **kwargs): pass
def npdefault(*args, **kwargs): pass
def object_rotate(*args, **kwargs): pass
def os(*args, **kwargs): pass
def path_object(*args, **kwargs): pass
def paths(*args, **kwargs): pass
def pi(*args, **kwargs): pass
def platform(*args, **kwargs): pass
def points(*args, **kwargs): pass
def pow(*args, **kwargs): pass
def print_anchor(*args, **kwargs): pass
def print_function(*args, **kwargs): pass
def print_to_string(*args, **kwargs): pass
def proj(*args, **kwargs): pass
def pyramid(*args, **kwargs): pass
def quad(*args, **kwargs): pass
def radians(*args, **kwargs): pass
def radio(*args, **kwargs): pass
def random(*args, **kwargs): pass
def rate(*args, **kwargs): pass
def rate_control(*args, **kwargs): pass
def ring(*args, **kwargs): pass
def rotate(*args, **kwargs): pass
def rotatecp(*args, **kwargs): pass
def roundc(*args, **kwargs): pass
def scalecp(*args, **kwargs): pass
def scene(*args, **kwargs): pass
def serveHTTP(*args, **kwargs): pass
def shape_object(*args, **kwargs): pass
def shapes(*args, **kwargs): pass
def shapespaths(*args, **kwargs): pass
def signature(*args, **kwargs): pass
def simulateDelay(*args, **kwargs): pass
def sin(*args, **kwargs): pass
def sinh(*args, **kwargs): pass
def sleep(*args, **kwargs): pass
def slider(*args, **kwargs): pass
def socket(*args, **kwargs): pass
def sphere(*args, **kwargs): pass
def sqrt(*args, **kwargs): pass
def standardAttributes(*args, **kwargs): pass
def sys(*args, **kwargs): pass
def tan(*args, **kwargs): pass
def tanh(*args, **kwargs): pass
def tau(*args, **kwargs): pass
def text(*args, **kwargs): pass
def textures(*args, **kwargs): pass
def threading(*args, **kwargs): pass
def time(*args, **kwargs): pass
def triangle(*args, **kwargs): pass
def trunc(*args, **kwargs): pass
def v(*args, **kwargs): pass
def vec(*args, **kwargs): pass
def vector(*args, **kwargs): pass
def version(*args, **kwargs): pass
def vertex(*args, **kwargs): pass
def vpython(*args, **kwargs): pass
def websocketserving(*args, **kwargs): pass
def wtext(*args, **kwargs): pass
